#!/usr/bin/env python3
"""
MSc-Level Analysis Suite for Kubernetes HPA Dissertation
Oliur Rahman Safwan | Leeds Beckett University | 2026

Produces:
  1. Statistical analysis (descriptive stats, effect size, CV, CI)
  2. Cost-performance model (pod-hours → cloud pricing)
  3. Publication-quality figures for Chapter 5
"""

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from collections import OrderedDict

plt.rcParams.update({
    'font.family': 'serif',
    'font.serif': ['Times New Roman', 'DejaVu Serif'],
    'font.size': 10,
    'figure.facecolor': 'white',
    'savefig.dpi': 200,
    'savefig.bbox': 'tight',
})

# =============================================================================
# SUBMISSION NOTE — READ BEFORE USE
# =============================================================================
# All 12 scenarios now use real CSV data verified from Locust output files.
# Values are sourced from resultsT{threshold}{workload}Run1_stats.csv
# GET / endpoint only — /stub_status excluded from analysis.
#
# All dissertation results reported in Chapter 5 (Table 5.1, Table 5.2,
# Table 5.3) are derived directly from raw Locust CSV output.
#
# This file is included as a record of the MSc-level analysis framework
# and figure generation approach. Triple-repeat values [v,v,v] are used
# to satisfy statistical functions designed for 3-run data.
# Figures generated by this script should be treated as illustrative
# since all scenarios have max_pods=1 and no scaling delay values.
# =============================================================================

OUT = r"C:\Users\admin\OneDrive - Leeds Beckett University\Desktop\dissertation\08_figures"

# ============================================================
# MASTER DATA — from verified CSV cross-check
# ============================================================
# Format: {scenario: {metric: [run1, run2, run3]}}
# REAL data from CSVs; projected runs use scaled estimates

data = {
    # ALL 12 SCENARIOS — REAL CSV DATA (GET / endpoint only)
    # Source: resultsT{threshold}{workload}Run1_stats.csv
    # Values verified against CSV files, single run per scenario.
    # Triple repeat [v,v,v] used to satisfy statistical functions.

    # Scenario 1: T50 Steady [REAL CSV: avg=8ms, fail=0.00%]
    1: {'threshold': 50, 'workload': 'Steady',
        'avg_resp': [8, 8, 8], 'fail_pct': [0.0, 0.0, 0.0],
        'max_cpu': [5, 5, 5], 'max_pods': [1, 1, 1],
        'scale_delay': [None, None, None], 'duration_min': 10,
        'pod_timeline': [(0, 1)]},
    # Scenario 2: T50 Step [REAL CSV: avg=17ms, fail=0.00%]
    2: {'threshold': 50, 'workload': 'Step',
        'avg_resp': [17, 17, 17], 'fail_pct': [0.0, 0.0, 0.0],
        'max_cpu': [5, 5, 5], 'max_pods': [1, 1, 1],
        'scale_delay': [None, None, None], 'duration_min': 16,
        'pod_timeline': [(0, 1)]},
    # Scenario 3: T50 Bursty [REAL CSV: avg=5ms, fail=0.00%]
    3: {'threshold': 50, 'workload': 'Bursty',
        'avg_resp': [5, 5, 5], 'fail_pct': [0.0, 0.0, 0.0],
        'max_cpu': [4, 4, 4], 'max_pods': [1, 1, 1],
        'scale_delay': [None, None, None], 'duration_min': 10,
        'pod_timeline': [(0, 1)]},
    # Scenario 4: T50 Spike [REAL CSV: avg=406ms, fail=8.70%]
    4: {'threshold': 50, 'workload': 'Spike',
        'avg_resp': [406, 406, 406], 'fail_pct': [8.70, 8.70, 8.70],
        'max_cpu': [33, 33, 33], 'max_pods': [1, 1, 1],
        'scale_delay': [None, None, None], 'duration_min': 9,
        'pod_timeline': [(0, 1)]},
    # Scenario 5: T70 Steady [REAL CSV: avg=42ms, fail=0.00%]
    5: {'threshold': 70, 'workload': 'Steady',
        'avg_resp': [42, 42, 42], 'fail_pct': [0.0, 0.0, 0.0],
        'max_cpu': [6, 6, 6], 'max_pods': [1, 1, 1],
        'scale_delay': [None, None, None], 'duration_min': 10,
        'pod_timeline': [(0, 1)]},
    # Scenario 6: T70 Step [REAL CSV: avg=19ms, fail=0.00%]
    6: {'threshold': 70, 'workload': 'Step',
        'avg_resp': [19, 19, 19], 'fail_pct': [0.0, 0.0, 0.0],
        'max_cpu': [5, 5, 5], 'max_pods': [1, 1, 1],
        'scale_delay': [None, None, None], 'duration_min': 16,
        'pod_timeline': [(0, 1)]},
    # Scenario 7: T70 Bursty [REAL CSV: avg=10ms, fail=0.00%]
    7: {'threshold': 70, 'workload': 'Bursty',
        'avg_resp': [10, 10, 10], 'fail_pct': [0.0, 0.0, 0.0],
        'max_cpu': [4, 4, 4], 'max_pods': [1, 1, 1],
        'scale_delay': [None, None, None], 'duration_min': 10,
        'pod_timeline': [(0, 1)]},
    # Scenario 8: T70 Spike [REAL CSV: avg=360ms, fail=8.78%]
    8: {'threshold': 70, 'workload': 'Spike',
        'avg_resp': [360, 360, 360], 'fail_pct': [8.78, 8.78, 8.78],
        'max_cpu': [39, 39, 39], 'max_pods': [1, 1, 1],
        'scale_delay': [None, None, None], 'duration_min': 9,
        'pod_timeline': [(0, 1)]},
    # Scenario 9: T90 Steady [REAL CSV: avg=15ms, fail=0.00%]
    9: {'threshold': 90, 'workload': 'Steady',
        'avg_resp': [15, 15, 15], 'fail_pct': [0.0, 0.0, 0.0],
        'max_cpu': [5, 5, 5], 'max_pods': [1, 1, 1],
        'scale_delay': [None, None, None], 'duration_min': 10,
        'pod_timeline': [(0, 1)]},
    # Scenario 10: T90 Step [REAL CSV: avg=5ms, fail=0.00%]
    10: {'threshold': 90, 'workload': 'Step',
         'avg_resp': [5, 5, 5], 'fail_pct': [0.0, 0.0, 0.0],
         'max_cpu': [4, 4, 4], 'max_pods': [1, 1, 1],
         'scale_delay': [None, None, None], 'duration_min': 16,
         'pod_timeline': [(0, 1)]},
    # Scenario 11: T90 Bursty [REAL CSV: avg=5ms, fail=0.00%]
    11: {'threshold': 90, 'workload': 'Bursty',
         'avg_resp': [5, 5, 5], 'fail_pct': [0.0, 0.0, 0.0],
         'max_cpu': [4, 4, 4], 'max_pods': [1, 1, 1],
         'scale_delay': [None, None, None], 'duration_min': 10,
         'pod_timeline': [(0, 1)]},
    # Scenario 12: T90 Spike [REAL CSV: avg=393ms, fail=8.61%]
    12: {'threshold': 90, 'workload': 'Spike',
         'avg_resp': [393, 393, 393], 'fail_pct': [8.61, 8.61, 8.61],
         'max_cpu': [33, 33, 33], 'max_pods': [1, 1, 1],
         'scale_delay': [None, None, None], 'duration_min': 9,
         'pod_timeline': [(0, 1)]},
}


# ============================================================
# 1. STATISTICAL ANALYSIS
# ============================================================
def statistical_analysis():
    print("=" * 80)
    print("  DESCRIPTIVE ANALYSIS — RESPONSE TIME & FAILURE RATE SUMMARY")
    print("  NOTE: Single run per scenario. Values [v,v,v] are repeated for")
    print("  compatibility with statistical functions — not independent runs.")
    print("=" * 80)
    
    # --- Per-scenario descriptive stats ---
    print(f"\n{'Sc':>3} {'Thresh':>6} {'WL':>7} | {'AvgResp':>8} {'SD':>6} {'CV':>6} | {'Fail%':>6} {'SD':>6} | {'ScaleDel':>8} {'SD':>6}")
    print("-" * 80)
    
    results = []
    for sc_id, sc in sorted(data.items()):
        avg_r = np.mean(sc['avg_resp'])
        sd_r = np.std(sc['avg_resp'], ddof=1)
        cv_r = (sd_r / avg_r * 100) if avg_r > 0 else 0
        
        avg_f = np.mean(sc['fail_pct'])
        sd_f = np.std(sc['fail_pct'], ddof=1)
        
        delays = [d for d in sc['scale_delay'] if d is not None]
        if delays:
            avg_d = np.mean(delays)
            sd_d = np.std(delays, ddof=1)
            delay_str = f"{avg_d:8.1f} {sd_d:6.1f}"
        else:
            avg_d = None
            sd_d = None
            delay_str = "     N/A    N/A"
        
        print(f"{sc_id:3d} {sc['threshold']:5d}% {sc['workload']:>7s} | {avg_r:8.1f} {sd_r:6.2f} {cv_r:5.1f}% | {avg_f:6.2f} {sd_f:6.3f} | {delay_str}")
        
        results.append({
            'id': sc_id, 'threshold': sc['threshold'], 'workload': sc['workload'],
            'avg_resp_mean': avg_r, 'avg_resp_sd': sd_r, 'avg_resp_cv': cv_r,
            'fail_mean': avg_f, 'fail_sd': sd_f,
            'delay_mean': avg_d, 'delay_sd': sd_d,
        })
    
    # --- Effect Size: Cohen's d ---
    # NOTE: Cohen's d below is ILLUSTRATIVE ONLY.
    # All values are single-run repeated as [v,v,v] so pooled_sd=0 for most
    # scenarios (identical values → d=0 or undefined). Only Spike scenarios
    # (which differ across thresholds) produce meaningful d values.
    # Do not cite these as statistically valid effect sizes.
    print(f"\n{'=' * 80}")
    print("  ILLUSTRATIVE EFFECT SIZE (Cohen's d) — Spike scenarios only are meaningful")
    print("  WARNING: Non-spike d values = 0 due to identical repeated data, not real effect")
    print(f"{'=' * 80}")
    print("  |d| < 0.2: negligible | 0.2-0.5: small | 0.5-0.8: medium | > 0.8: large\n")
    
    workloads = ['Steady', 'Step', 'Bursty', 'Spike']
    thresholds = [50, 70, 90]
    
    for wl in workloads:
        scenarios_by_thresh = {}
        for sc_id, sc in data.items():
            if sc['workload'] == wl:
                scenarios_by_thresh[sc['threshold']] = sc
        
        print(f"  {wl} workload:")
        for i, t1 in enumerate(thresholds):
            for t2 in thresholds[i+1:]:
                if t1 in scenarios_by_thresh and t2 in scenarios_by_thresh:
                    r1 = scenarios_by_thresh[t1]['avg_resp']
                    r2 = scenarios_by_thresh[t2]['avg_resp']
                    pooled_sd = np.sqrt((np.var(r1, ddof=1) + np.var(r2, ddof=1)) / 2)
                    if pooled_sd > 0:
                        d = (np.mean(r1) - np.mean(r2)) / pooled_sd
                    else:
                        d = 0
                    
                    magnitude = "negligible" if abs(d) < 0.2 else "small" if abs(d) < 0.5 else "medium" if abs(d) < 0.8 else "LARGE"
                    print(f"    T{t1}% vs T{t2}% (Avg Response): d = {d:+.2f} ({magnitude})")
        
        f1 = scenarios_by_thresh[50]['fail_pct']
        f3 = scenarios_by_thresh[90]['fail_pct']
        pooled_sd_f = np.sqrt((np.var(f1, ddof=1) + np.var(f3, ddof=1)) / 2)
        if pooled_sd_f > 0:
            d_f = (np.mean(f1) - np.mean(f3)) / pooled_sd_f
            magnitude_f = "negligible" if abs(d_f) < 0.2 else "small" if abs(d_f) < 0.5 else "medium" if abs(d_f) < 0.8 else "LARGE"
            print(f"    T50% vs T90% (Failure Rate):  d = {d_f:+.2f} ({magnitude_f})")
        print()
    
    # --- 95% Confidence Intervals ---
    # NOTE: CI values below are NOT statistically valid.
    # All runs are identical repeats [v,v,v] so SE=0 and CI=[mean,mean].
    # Included for framework completeness only — do not cite in dissertation.
    print(f"{'=' * 80}")
    print("  ILLUSTRATIVE CI (single-run data — intervals are not statistically meaningful)")
    print(f"{'=' * 80}")
    
    try:
        from scipy import stats as scipy_stats
        t_crit = scipy_stats.t.ppf(0.975, df=2)
        print(f"\n  t-critical (95%, df=2): {t_crit:.3f}")
        print(f"  NOTE: SE=0 for all non-varied scenarios → CI collapses to point estimate\n")
        print(f"  {'Scenario':>35} {'Metric':>8} {'Mean':>8} {'CI':>20}")
        print(f"  {'-'*75}")
        for sc_id, sc in sorted(data.items()):
            vals = sc['avg_resp']
            mean = np.mean(vals)
            se = np.std(vals, ddof=1) / np.sqrt(3)
            ci_low = mean - t_crit * se
            ci_high = mean + t_crit * se
            label = f"S{sc_id} T{sc['threshold']}% {sc['workload']}"
            print(f"  {label:>35} {'AvgResp':>8} {mean:8.1f} [{ci_low:8.1f}, {ci_high:8.1f}]")
    except ImportError:
        print("  scipy not available — skipping CI")
    
    return results


# ============================================================
# 2. COST-PERFORMANCE MODEL
# ============================================================
def cost_performance_model():
    print(f"\n{'=' * 80}")
    print("  COST-PERFORMANCE MODEL — Pod-Hours → Cloud Pricing")
    print(f"{'=' * 80}")
    
    # AWS EKS pricing (t3.medium: $0.0416/hr, ~2 vCPU, 4GB)
    # Each pod uses 100m CPU = 0.1 vCPU
    # Cost per pod-hour on t3.medium: $0.0416 * (0.1/2) = $0.00208
    # But more realistically, billing is per-node, so:
    # Node cost per hour: $0.0416 (on-demand t3.medium)
    # Pods per node: ~20 (2000m / 100m)
    # Effective cost per pod-hour: $0.0416 / 20 = $0.00208
    
    COST_PER_POD_HOUR = 0.00208  # USD, AWS t3.medium effective
    GCP_COST_PER_POD_HOUR = 0.00195  # GCP e2-medium effective
    AZURE_COST_PER_POD_HOUR = 0.00215  # Azure B2s effective
    
    print(f"\n  Pricing basis:")
    print(f"    AWS EKS (t3.medium):    ${COST_PER_POD_HOUR:.5f}/pod-hour")
    print(f"    GCP GKE (e2-medium):    ${GCP_COST_PER_POD_HOUR:.5f}/pod-hour")
    print(f"    Azure AKS (B2s):        ${AZURE_COST_PER_POD_HOUR:.5f}/pod-hour")
    print(f"    Pod resource request:   100m CPU (0.1 vCPU)")
    print()
    
    # Compute pod-hours for each scenario
    print(f"  {'Sc':>3} {'Thresh':>6} {'WL':>7} {'Dur(min)':>8} {'MaxPods':>7} {'Pod-Hrs':>8} {'AWS$/run':>9} {'$/month':>9} {'$/year':>9}")
    print(f"  {'-' * 80}")
    
    cost_by_threshold = {50: [], 70: [], 90: []}
    cost_data = []
    
    for sc_id, sc in sorted(data.items()):
        duration_hrs = sc['duration_min'] / 60.0
        max_pods = int(np.mean(sc['max_pods']))
        
        # Compute pod-hours from timeline
        timeline = sc['pod_timeline']
        pod_hours = 0
        for i in range(len(timeline)):
            t_start = timeline[i][0]
            pods = timeline[i][1]
            if i + 1 < len(timeline):
                t_end = timeline[i+1][0]
            else:
                t_end = sc['duration_min']
            segment_hours = (t_end - t_start) / 60.0
            pod_hours += pods * segment_hours
        
        aws_cost = pod_hours * COST_PER_POD_HOUR
        
        # Monthly projection: assume workload repeats
        # Steady: 8hrs/day * 22 days = 176 hrs/month
        # Step: 4 times/day * 22 days = 88 occurrences
        # Bursty: continuous, 720 hrs/month
        # Spike: 2 times/day * 22 days = 44 occurrences
        if sc['workload'] == 'Steady':
            monthly_multiplier = 176 / (sc['duration_min'] / 60)
        elif sc['workload'] == 'Step':
            monthly_multiplier = 88
        elif sc['workload'] == 'Bursty':
            monthly_multiplier = 720 / (sc['duration_min'] / 60)
        else:  # Spike
            monthly_multiplier = 44
        
        monthly_cost = aws_cost * monthly_multiplier
        yearly_cost = monthly_cost * 12
        
        cost_by_threshold[sc['threshold']].append(monthly_cost)
        cost_data.append({
            'id': sc_id, 'threshold': sc['threshold'], 'workload': sc['workload'],
            'pod_hours': pod_hours, 'aws_cost': aws_cost,
            'monthly': monthly_cost, 'yearly': yearly_cost
        })
        
        print(f"  {sc_id:3d} {sc['threshold']:5d}% {sc['workload']:>7s} {sc['duration_min']:7d}m {max_pods:7d} {pod_hours:8.3f} ${aws_cost:8.5f} ${monthly_cost:8.2f} ${yearly_cost:8.2f}")
    
    # Summary by threshold
    print(f"\n  {'=' * 60}")
    print(f"  THRESHOLD COST COMPARISON (monthly, all workloads combined)")
    print(f"  {'=' * 60}")
    for t in [50, 70, 90]:
        total = sum(cost_by_threshold[t])
        print(f"    T{t}%: ${total:.2f}/month  |  ${total*12:.2f}/year")
    
    # Savings calculation
    t50_total = sum(cost_by_threshold[50])
    t70_total = sum(cost_by_threshold[70])
    t90_total = sum(cost_by_threshold[90])
    
    # NOTE: All 12 Nginx scenarios used max_pods=1 — HPA never triggered.
    # Therefore pod-hour costs are equal across all thresholds in practice.
    # Any cost differences below arise from the spike scenario response time
    # differences only (different avg_resp affects theoretical efficiency).
    # Cost savings percentages should NOT be presented as empirical findings.
    # They are illustrative projections of what savings WOULD occur if scaling
    # had been triggered. Treat as theoretical framework only.
    print(f"\n  COST MODEL NOTE: All scenarios used 1 pod — no scaling observed.")
    print(f"  Values below are theoretical projections, not empirical measurements.")
    print(f"\n  PROJECTED SAVINGS (theoretical):")
    if t50_total > t90_total:
        saving_50_90 = t50_total - t90_total
        print(f"    T90% projected saving: ${saving_50_90:.2f}/month vs T50% ({saving_50_90/t50_total*100:.1f}% — theoretical only)")
    if t50_total > t70_total:
        saving_50_70 = t50_total - t70_total
        print(f"    T70% projected saving: ${saving_50_70:.2f}/month vs T50% ({saving_50_70/t50_total*100:.1f}% — theoretical only)")
    
    return cost_data


# ============================================================
# 3. FIGURES
# ============================================================

def fig_statistical_comparison():
    """Box plot of response times by threshold and workload."""
    fig, axes = plt.subplots(1, 4, figsize=(14, 5), sharey=False)
    fig.suptitle('Figure 5.5: Response Time Distribution by Threshold and Workload\n(Single run per scenario — repeated values used for statistical functions)', 
                 fontsize=12, fontweight='bold')
    
    workloads = ['Steady', 'Step', 'Bursty', 'Spike']
    colors = {'50': '#42A5F5', '70': '#66BB6A', '90': '#FFA726'}
    
    for i, wl in enumerate(workloads):
        ax = axes[i]
        positions = []
        values = []
        cols = []
        labels = []
        
        for j, t in enumerate([50, 70, 90]):
            for sc_id, sc in data.items():
                if sc['threshold'] == t and sc['workload'] == wl:
                    positions.append(j)
                    values.append(sc['avg_resp'])
                    cols.append(colors[str(t)])
                    labels.append(f'T{t}%')
                    break
        
        bp = ax.boxplot(values, positions=range(3), widths=0.5, patch_artist=True,
                       medianprops=dict(color='black', linewidth=2))
        for patch, color in zip(bp['boxes'], [colors['50'], colors['70'], colors['90']]):
            patch.set_facecolor(color)
            patch.set_alpha(0.7)
        
        ax.set_title(wl, fontsize=11, fontweight='bold')
        ax.set_xticks(range(3))
        ax.set_xticklabels(['50%', '70%', '90%'], fontsize=9)
        ax.set_xlabel('CPU Threshold')
        if i == 0:
            ax.set_ylabel('Avg Response Time (ms)')
        ax.grid(axis='y', alpha=0.3)
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
    
    plt.tight_layout()
    fig.savefig(f'{OUT}/fig55_statistical_comparison.png')
    plt.close()
    print("✓ Figure 5.5: Statistical comparison")


def fig_effect_size_heatmap():
    """Effect size heatmap across workloads and threshold pairs."""
    fig, ax = plt.subplots(figsize=(8, 5))
    
    workloads = ['Steady', 'Step', 'Bursty', 'Spike']
    pairs = ['50% vs 70%', '50% vs 90%', '70% vs 90%']
    
    effect_matrix = np.zeros((4, 3))
    
    for i, wl in enumerate(workloads):
        scenarios = {sc['threshold']: sc for sc in data.values() if sc['workload'] == wl}
        pair_thresholds = [(50, 70), (50, 90), (70, 90)]
        for j, (t1, t2) in enumerate(pair_thresholds):
            r1 = scenarios[t1]['avg_resp']
            r2 = scenarios[t2]['avg_resp']
            pooled_sd = np.sqrt((np.var(r1, ddof=1) + np.var(r2, ddof=1)) / 2)
            if pooled_sd > 0:
                effect_matrix[i, j] = abs((np.mean(r1) - np.mean(r2)) / pooled_sd)
            else:
                effect_matrix[i, j] = 0
    
    im = ax.imshow(effect_matrix, cmap='YlOrRd', aspect='auto', vmin=0, vmax=5)
    
    ax.set_xticks(range(3))
    ax.set_xticklabels(pairs, fontsize=10)
    ax.set_yticks(range(4))
    ax.set_yticklabels(workloads, fontsize=10)
    
    for i in range(4):
        for j in range(3):
            val = effect_matrix[i, j]
            magnitude = "neg." if val < 0.2 else "small" if val < 0.5 else "med." if val < 0.8 else "LARGE"
            color = 'white' if val > 2 else 'black'
            ax.text(j, i, f'd={val:.1f}\n({magnitude})', ha='center', va='center', 
                   fontsize=9, fontweight='bold', color=color)
    
    plt.colorbar(im, ax=ax, label="Cohen's d (absolute)")
    ax.set_title("Figure 5.6: Illustrative Effect Size Heatmap — Threshold Impact on Response Time\n(Cohen's d — Spike scenarios only are statistically meaningful; others show d=0)", 
                fontsize=11, fontweight='bold')
    
    plt.tight_layout()
    fig.savefig(f'{OUT}/fig56_effect_size_heatmap.png')
    plt.close()
    print("✓ Figure 5.6: Effect size heatmap")


def fig_cost_performance():
    """Cost-performance Pareto frontier."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5.5))
    fig.suptitle('Figure 5.7: Cost-Performance Analysis by Threshold Configuration',
                fontsize=12, fontweight='bold')
    
    colors = {50: '#42A5F5', 70: '#66BB6A', 90: '#FFA726'}
    markers = {'Steady': 'o', 'Step': 's', 'Bursty': 'D', 'Spike': '^'}
    
    COST_PER_POD_HOUR = 0.00208
    
    # LEFT: Scatter — monthly cost vs avg failure rate
    for sc_id, sc in data.items():
        duration_hrs = sc['duration_min'] / 60
        max_pods = np.mean(sc['max_pods'])
        pod_hours = 0
        for i, (t, p) in enumerate(sc['pod_timeline']):
            t_end = sc['pod_timeline'][i+1][0] if i+1 < len(sc['pod_timeline']) else sc['duration_min']
            pod_hours += p * (t_end - t) / 60
        
        cost = pod_hours * COST_PER_POD_HOUR
        fail = np.mean(sc['fail_pct'])
        
        ax1.scatter(cost * 1000, fail, c=colors[sc['threshold']], 
                   marker=markers[sc['workload']], s=120, edgecolors='black', linewidth=0.8,
                   zorder=3)
    
    # Legend
    for t, c in colors.items():
        ax1.scatter([], [], c=c, s=80, label=f'T{t}%', edgecolors='black', linewidth=0.8)
    for wl, m in markers.items():
        ax1.scatter([], [], c='gray', marker=m, s=80, label=wl, edgecolors='black', linewidth=0.8)
    
    ax1.set_xlabel('Cost per Run (× $0.001)', fontsize=10)
    ax1.set_ylabel('Failure Rate (%)', fontsize=10)
    ax1.set_title('(a) Cost vs Failure Rate', fontsize=11)
    ax1.legend(fontsize=8, ncol=2, loc='upper right')
    ax1.grid(alpha=0.3)
    ax1.spines['top'].set_visible(False)
    ax1.spines['right'].set_visible(False)
    
    # RIGHT: Bar chart — monthly cost by threshold
    thresh_monthly = {}
    for t in [50, 70, 90]:
        total = 0
        for sc in data.values():
            if sc['threshold'] == t:
                pod_hours = 0
                for i, (tm, p) in enumerate(sc['pod_timeline']):
                    t_end = sc['pod_timeline'][i+1][0] if i+1 < len(sc['pod_timeline']) else sc['duration_min']
                    pod_hours += p * (t_end - tm) / 60
                total += pod_hours * COST_PER_POD_HOUR
        thresh_monthly[t] = total * 720  # scale to monthly
    
    bars = ax2.bar(['50%\n(Conservative)', '70%\n(Standard)', '90%\n(Aggressive)'],
                   [thresh_monthly[50], thresh_monthly[70], thresh_monthly[90]],
                   color=[colors[50], colors[70], colors[90]],
                   edgecolor='black', linewidth=0.8)
    
    for bar, t in zip(bars, [50, 70, 90]):
        h = bar.get_height()
        ax2.text(bar.get_x() + bar.get_width()/2., h + 0.001,
                f'${thresh_monthly[t]:.3f}', ha='center', fontsize=10, fontweight='bold')
    
    ax2.set_ylabel('Estimated Monthly Cost (USD)', fontsize=10)
    ax2.set_title('(b) Monthly Infrastructure Cost by Threshold', fontsize=11)
    ax2.grid(axis='y', alpha=0.3)
    ax2.spines['top'].set_visible(False)
    ax2.spines['right'].set_visible(False)
    
    # Savings annotation
    saving = thresh_monthly[50] - thresh_monthly[90]
    if saving > 0:
        ax2.annotate(f'T90% projected\n${saving:.3f}/mo\nvs T50%\n(theoretical)', 
                    xy=(2, thresh_monthly[90]), xytext=(1.5, thresh_monthly[50]*0.8),
                    fontsize=9, fontweight='bold', color='#E65100',
                    arrowprops=dict(arrowstyle='->', color='#E65100'))
    
    plt.tight_layout()
    fig.savefig(f'{OUT}/fig57_cost_performance.png')
    plt.close()
    print("✓ Figure 5.7: Cost-performance analysis")


# NOTE: fig_scaling_delay() has been removed.
# All 12 scenarios had scale_delay = None (HPA never triggered for Nginx).
# A scaling delay figure cannot be generated from this data.
# Any scaling delay values in the dissertation (Section 5.5.2, Table 5.2)
# are theoretical projections based on HPA control loop analysis,
# not empirically measured values.


# ============================================================
# RUN ALL
# ============================================================
import os
os.makedirs(OUT, exist_ok=True)

try:
    results = statistical_analysis()
except ImportError:
    print("NOTE: scipy not available, skipping CI calculation")
    results = statistical_analysis()

cost_data = cost_performance_model()

fig_statistical_comparison()
fig_effect_size_heatmap()
fig_cost_performance()
# fig_scaling_delay() — REMOVED: no scaling was observed in any scenario

print(f"\n{'=' * 80}")
print("  ALL MSc-LEVEL ANALYSES COMPLETE")
print(f"{'=' * 80}")